# -*- coding: utf-8 -*-
"""SuperMarket_Sales_AINGenX.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V7lqelmeJ3b-ao9OhgZeYMATMI_Ep9Ub
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
!pip install calmap
import calmap

"""**Context**

The growth of supermarkets in most populated cities are increasing and market competitions are also high. The dtataset is one of the historical sales of supermarket company which has recorded in 3 different branches for 3 months data

**Data Dictionary**

 *Invoice id:*
 Computer generated sales slip invoice identification number

 *Branch:*
  Branch of supercenter (3 branches are available identified by A,B and C)

 *City:*
 Location of Supercenter

  *Customer type:*
  Type of customers Gender: Gender type of Customer
  
  *Product line:*
  General item categorization group
  
 *Unit Price:*
 Price of each product in USD

*Quantity:* Number of products purchased

*Tax:*
5% tax fee for customer buying

*COGS:*
Cost of Goods Sold
"""

df=pd.read_csv('/content/supermarket_sales - Sheet1.csv')

df.head(10)

df.tail(10)

df.columns

df.dtypes

df['Date']=pd.to_datetime(df['Date'])

df.set_index('Date',inplace=True)

df.head()

df.describe()

"""**Univariate Analysis**

What does the distribution of customer ratings looks like?
"""

sns.distplot(df['Rating'])

sns.distplot(df['Rating'])
plt.axvline(x=np.mean(df['Rating']),c='red',ls='--')
plt.axvline(x=np.percentile(df['Rating'],25),c='green',ls='--')
plt.axvline(x=np.percentile(df['Rating'],75),c='green',ls='--')
plt.show()

df.hist(figsize=(10,10))

"""Do aggregate sales numbers differ by much between branches?"""

sns.countplot(x='Branch', data=df)

df['Branch'].value_counts()

sns.countplot(x='Payment', data=df)

"""**Bivariate Analysis**

Is there a relationship between gross income and customer range
"""

sns.regplot(x='Rating', y='gross income', data=df)

sns.boxplot(x=df['Branch'], y=df['gross income'])

sns.boxplot(x=df['Gender'],y=df['gross income'])

"""Is there a noticeable time trend in gross income?"""

df.head()

df.groupby(df.index)['gross income'].mean()

mean_gross_income = df.groupby(df.index)['gross income'].mean()

sns.lineplot(x=mean_gross_income.index, y=mean_gross_income)

sns.pairplot(df)

"""Dealing with duplicate rows and missing values"""

df.duplicated().sum()

df[df.duplicated()==True]

df.drop_duplicates(inplace=True)

df.isna().sum()

df.fillna(df.mode().iloc[0],inplace=True)